<?php

namespace ContainerR9eHRSW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XrZ71s7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.xrZ71s7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xrZ71s7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bdcRepo' => ['privates', 'App\\Repository\\BondeCommandeRepository', 'getBondeCommandeRepositoryService', true],
        ], [
            'bdcRepo' => 'App\\Repository\\BondeCommandeRepository',
        ]);
    }
}
