<?php

namespace ContainerR9eHRSW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GquKO1UService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gquKO1U' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gquKO1U'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bdlRepo' => ['privates', 'App\\Repository\\BonDeLivraisonRepository', 'getBonDeLivraisonRepositoryService', true],
        ], [
            'bdlRepo' => 'App\\Repository\\BonDeLivraisonRepository',
        ]);
    }
}
