<?php

namespace ContainerR9eHRSW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PM7aqTAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pM7aqTA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pM7aqTA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'sortieRepo' => ['privates', 'App\\Repository\\SortieItemRepository', 'getSortieItemRepositoryService', true],
        ], [
            'sortieRepo' => 'App\\Repository\\SortieItemRepository',
        ]);
    }
}
