<?php

namespace Container0FQFD5I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YGJWp_CService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YGJWp.C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YGJWp.C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'bdc' => ['privates', '.errored..service_locator.YGJWp.C.App\\Entity\\BondeCommande', NULL, 'Cannot autowire service ".service_locator.YGJWp.C": it references class "App\\Entity\\BondeCommande" but no such service exists.'],
            'medicRepo' => ['privates', 'App\\Repository\\MedicItemsRepository', 'getMedicItemsRepositoryService', true],
            'mr' => ['privates', 'App\\Repository\\MedicamentRepository', 'getMedicamentRepositoryService', true],
        ], [
            'bdc' => 'App\\Entity\\BondeCommande',
            'medicRepo' => 'App\\Repository\\MedicItemsRepository',
            'mr' => 'App\\Repository\\MedicamentRepository',
        ]);
    }
}
