<?php

namespace Container0FQFD5I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WsjWySEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WsjWySE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WsjWySE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medic' => ['privates', '.errored..service_locator.WsjWySE.App\\Entity\\Medicament', NULL, 'Cannot autowire service ".service_locator.WsjWySE": it references class "App\\Entity\\Medicament" but no such service exists.'],
            'mr' => ['privates', 'App\\Repository\\MedicamentRepository', 'getMedicamentRepositoryService', true],
        ], [
            'medic' => 'App\\Entity\\Medicament',
            'mr' => 'App\\Repository\\MedicamentRepository',
        ]);
    }
}
