<?php

namespace Container0FQFD5I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TTWX3aIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TTWX3aI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TTWX3aI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'medic' => ['privates', '.errored.TtYIZGJ', NULL, 'Cannot determine controller argument for "App\\Controller\\BonController::autoUpdateStock()": the $medic argument is type-hinted with the non-existent class or interface: "App\\Controller\\Medicament". Did you forget to add a use statement?'],
        ], [
            'medic' => '?',
        ]);
    }
}
