<?php

namespace Container0FQFD5I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_TtYIZGJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.TtYIZGJ' shared service.
     *
     * @return \App\Controller\Medicament
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\BonController::autoUpdateStock()": the $medic argument is type-hinted with the non-existent class or interface: "App\\Controller\\Medicament". Did you forget to add a use statement?');
    }
}
