<?php

namespace Container0FQFD5I;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBondeCommandeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.YGJWp.C.App\Entity\BondeCommande' shared service.
     *
     * @return \App\Entity\BondeCommande
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.YGJWp.C": it references class "App\\Entity\\BondeCommande" but no such service exists.');
    }
}
