<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Medicament extends \App\Entity\Medicament implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'dci', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'pa', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'pv', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'dosage', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'forme', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'avoir', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'jouRupture', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'max', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'peremption', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'min', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'ItemMedicament', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'sortieItems', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'etat'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'dci', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'code', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'pa', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'pv', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'dosage', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'forme', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'categorie', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'stock', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'avoir', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'jouRupture', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'max', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'peremption', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'min', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'ItemMedicament', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'sortieItems', '' . "\0" . 'App\\Entity\\Medicament' . "\0" . 'etat'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Medicament $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDci(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDci', []);

        return parent::getDci();
    }

    /**
     * {@inheritDoc}
     */
    public function setDci(?string $dci): ?\App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDci', [$dci]);

        return parent::setDci($dci);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode(?string $code): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getPa(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPa', []);

        return parent::getPa();
    }

    /**
     * {@inheritDoc}
     */
    public function setPa(float $pa): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPa', [$pa]);

        return parent::setPa($pa);
    }

    /**
     * {@inheritDoc}
     */
    public function getPv(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPv', []);

        return parent::getPv();
    }

    /**
     * {@inheritDoc}
     */
    public function setPv(float $pv): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPv', [$pv]);

        return parent::setPv($pv);
    }

    /**
     * {@inheritDoc}
     */
    public function getDosage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDosage', []);

        return parent::getDosage();
    }

    /**
     * {@inheritDoc}
     */
    public function setDosage(string $dosage): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDosage', [$dosage]);

        return parent::setDosage($dosage);
    }

    /**
     * {@inheritDoc}
     */
    public function getForme(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getForme', []);

        return parent::getForme();
    }

    /**
     * {@inheritDoc}
     */
    public function setForme(string $forme): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setForme', [$forme]);

        return parent::setForme($forme);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorie(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorie', []);

        return parent::getCategorie();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorie(?string $categorie): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorie', [$categorie]);

        return parent::setCategorie($categorie);
    }

    /**
     * {@inheritDoc}
     */
    public function getStock(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStock', []);

        return parent::getStock();
    }

    /**
     * {@inheritDoc}
     */
    public function setStock(int $stock): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStock', [$stock]);

        return parent::setStock($stock);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvoir(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvoir', []);

        return parent::getAvoir();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvoir(int $avoir): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvoir', [$avoir]);

        return parent::setAvoir($avoir);
    }

    /**
     * {@inheritDoc}
     */
    public function getJouRupture(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJouRupture', []);

        return parent::getJouRupture();
    }

    /**
     * {@inheritDoc}
     */
    public function setJouRupture(?int $jouRupture): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJouRupture', [$jouRupture]);

        return parent::setJouRupture($jouRupture);
    }

    /**
     * {@inheritDoc}
     */
    public function getMax(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMax', []);

        return parent::getMax();
    }

    /**
     * {@inheritDoc}
     */
    public function setMax(?int $max): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMax', [$max]);

        return parent::setMax($max);
    }

    /**
     * {@inheritDoc}
     */
    public function getPeremption(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPeremption', []);

        return parent::getPeremption();
    }

    /**
     * {@inheritDoc}
     */
    public function setPeremption($peremption): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPeremption', [$peremption]);

        return parent::setPeremption($peremption);
    }

    /**
     * {@inheritDoc}
     */
    public function getMin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMin', []);

        return parent::getMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setMin(?int $min): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMin', [$min]);

        return parent::setMin($min);
    }

    /**
     * {@inheritDoc}
     */
    public function getItemMedicament(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getItemMedicament', []);

        return parent::getItemMedicament();
    }

    /**
     * {@inheritDoc}
     */
    public function addItemMedicament(\App\Entity\MedicItems $itemMedicament): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addItemMedicament', [$itemMedicament]);

        return parent::addItemMedicament($itemMedicament);
    }

    /**
     * {@inheritDoc}
     */
    public function removeItemMedicament(\App\Entity\MedicItems $itemMedicament): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeItemMedicament', [$itemMedicament]);

        return parent::removeItemMedicament($itemMedicament);
    }

    /**
     * {@inheritDoc}
     */
    public function getSortieItems(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSortieItems', []);

        return parent::getSortieItems();
    }

    /**
     * {@inheritDoc}
     */
    public function addSortieItem(\App\Entity\SortieItem $sortieItem): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSortieItem', [$sortieItem]);

        return parent::addSortieItem($sortieItem);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSortieItem(\App\Entity\SortieItem $sortieItem): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSortieItem', [$sortieItem]);

        return parent::removeSortieItem($sortieItem);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(string $etat): \App\Entity\Medicament
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

}
