<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR9eHRSW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR9eHRSW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR9eHRSW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR9eHRSW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR9eHRSW\App_KernelDevDebugContainer([
    'container.build_hash' => 'R9eHRSW',
    'container.build_id' => '3a073579',
    'container.build_time' => 1630250658,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR9eHRSW');
